version: "3.8"
services:
    users:
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            DB_HOST: users_db
            DB_DATABASE: users
            DB_PASSWORD: root
        command: "php artisan serve --host=0.0.0.0"
        depends_on:
            - users_db
        ports:
            - 8000:8000
        volumes:
            - .:/home
        networks:
            - users
    users_db:
        image: mysql:8.0
        environment:
            MYSQL_DATABASE: users
            MYSQL_PASSWORD: root
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - ./storage/dbdata:/var/lib/mysql
        ports:
            - 33069:3306
        networks:
            - users
networks:
    users:
